### PR TITLE
Add error and warning hooks to iCal parser

### PR DESCRIPTION
**Pull request by bhwebworks**
Added hooks to report_error and report_warning functions. Intention is to allow an email to be sent to site administrator notifying of iCal syncing error or warning.

### CODE REVIEW

**Comment by bhwebworks** [comment]
Any chance this pull request will be accepted?

**Comment by stephenharris** [comment]
Hi @bhwebworks 

Sorry I've taken so long to get back to you on this. Unfortunately your commit has changed the entire file (probably to do with line endings??). Which lines(s) have you edited?

**Comment by bhwebworks** [comment]
Not sure what happened with that file, but I added a do_action at lines 516 and 543.

**Comment by stephenharris** [comment]
You realise that will trigger for each every warning/error in the feed. Generally one error stops play, but that's not necessarily the case. An iCal feed can every a number of warnings.

Sorry, I've only now just released what the intention was here. Wouldn't this hook be better: https://github.com/bhwebworks/Event-Organiser/blob/ical-sync-error-add-hooks/includes/class-eo-ical-parser.php#L239

You can check for errors and warnings after the entire feed has been parsed and send one e-mail for the entire feed.

**Comment by bhwebworks** [comment]
I did realize that about every error or warning, and was going to turn off the warnings emails after "if and when" I received any.

So to use that existing hook I would do something like this?

`add_action( 'eventorganiser_ical_feed_parsed', 'send_email_if_errors' );

function send_email_if_errors( $ical_parser ) {
     if ( ! empty( $ical_parser->errors ) ) {
          // send email	
     }
}`

**Comment by bhwebworks** [comment]
Regarding that class-eo-ical-parser.php file, when I open it for editing here on GitHub in Chrome, it shows 1,257 changes before I actually make any changes. I tried that on several other files in the includes directory and they seemed to be fine, with no changes.

**Comment by stephenharris** [comment]
That's right. Regarding the changes, it probably is line encoding or something.

**Pull request closed without merging**
