### PR TITLE
Add an action for plugins to add to EO's core metabox fields

### PR DESCRIPTION
**Pull request by boonebgorges**
I'd like an easy way to add additional fields to the metabox interface. Could we have one like what I've suggested in this PR? Happy to take suggestions on naming conventions, passed parameters, etc. Thanks for considering!

### CODE REVIEW

**Comment by boonebgorges** [comment]
Ergh, sorry for the messy PR. Let me try to fix it...

**Comment by boonebgorges** [comment]
That's better :)

**Comment by stephenharris** [comment]
I will probably rename this `eventorganiser_metabox_after_core_fields` as it leaves open the possibility of similar hooks in other contexts.

**Comment by boonebgorges** [comment]
Sure thing, @stephenharris. I've just rebuilt my PR using the new name, for your merging pleasure :) Thanks for considering.

**Comment by stephenharris** [comment]
Thanks for the update. This will be in 3.1, but no ETA as of yet (there's a very minor 3.0.5 update due first).

**Pull request merged**
